version: '3.1'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=DjJXk*^8iNDRnpX5uv
      - MYSQL_DATABASE=projetopo
      - MYSQL_USER=projetopo
      - MYSQL_PASSWORD=DjJXk*^8iNDRnpX5uv
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
